name: typecheck-typescript

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Type checking with TypeScript
      run: npm run type-check # Assuming you have a script named "type-check" in your package.json

    # Add more steps for testing, building, etc.